module.exports = {
  helpMessage: `
\`\`\`
List of commands :
 - @StalineBot : Write a quote
 - !anthem : play anthem song
 - !exile [@someone] : Remove all roles an give Contre révolitionnaire role
 - !international : play international song
 - !leave : make bot leave vocal-channel
 - !meme : Display meme image
 - !propagande : Display propagande image
 - !promote [@someone] : Give rights to someone
 - !purge [@someone] : Kick someone from the Discord
 - !q : answer yes or no
 - !rate : give a number between 0 and 10 to rate something
 - !help : Display this message
\`\`\`
`,
  rate: [
    '0/10',
    '1/10',
    '2/10',
    '3/10',
    '4/10',
    '5/10',
    '6/10',
    '7/10',
    '8/10',
    '9/10',
    '10/10',
  ],
  quotes: [
    'Everybody has a right to be stupid, but some people abuse the privilege.',
    'Ideas are more powerful than guns. We would not let our enemies have guns, why should we let them have ideas.',
    'It is difficult for me to imagine what “personal liberty” is enjoyed by an unemployed hungry person. True freedom can only be where there is no exploitation and oppression of one person by another; where there is not unemployment, and where a person is not living in fear of losing his job, his home and his bread. Only in such a society personal and any other freedom can exist for real and not on paper.',
    'When there\'s a person, there\'s a problem. When there\'s no person, there\'s no problem. Josef Stalin',
    'It\'s not the people who vote that count. It\'s the people who count the votes.',
    'The death of one man is tragic, but the death of thousands is statistic.',
    'Great Britain provided time; the United States provided money and Soviet Russia provided blood.',
    'Divide the world into regional groups as a transitional stage to world government. Populations will more readily abandon their national loyalty to a vague regional loyalty than they will for a world authority. Later the regions can be brought together all the way into a single world dictatorship.',
    'Education is a weapon the effect of which is determined by the hands which wield it, by who is to be struck down.',
    'This creature softened my heart of stone. She died and with her died my last warm feelings for humanity.',
    'It is not heroes that make history, but history that makes heroes.',
    'When we hang the capitalists they will sell us the rope we use.',
    'To choose one\'s victims, to prepare one\'s plan minutely, to slake an implacable vengeance, and then to go to bed... There is nothing sweeter in the world.',
    'By May, 1st, 1937, there should not be one single church left within the borders of Soviet Russia, and the idea of God will have been banished from the Soviet Union as a remnant of the Middle Ages, which has been used for the purpose of oppressing the working classes.',
    'The press must grow day in and day out - it is our Party\'s sharpest and most powerful weapon.',
    'Of all the treasures a state can possess, the human lives of its citizens are for us the most precious.',
    'I believe in one thing only, the power of human will.',
    'The only real power comes out of a long rifle.',
    'Die, but do not retreat.',
    'Nobody respects a country with a poor army, but everybody respects a country with a good army. I raise my toast to the Finnish army',
    'I trust no one, not even myself.',
    'Do you remember the tsar? Well, I‘m like a tsar.',
    'How do you expect the Germans to revolt when they don\'t even dare walk on the grass?',
    'Gratitude is a sickness suffered by dogs.',
    '[After Communism succeeds] ...then, there will come a peace across the earth.',
    'It takes a brave man to be a coward in the Red Army.',
    'The production of souls is more important than the production of tanks.... And therefore I raise my glass to you, writers, the engineers of the human soul.',
    'He who votes does not have power. He who counts the votes has power.',
    'The leaders come and go, but the people remain. Only the people are immortal',
    'A man\'s eyes should be torn out if he can only see the past',
    'The United States should get rid of its militias.',
    'Ah, these diplomats! What chatterboxes! There\'s only one way to shut them up - cut them down with machine guns. Bulganin, go and get me one!',
    'Words are one thing - deeds something entirely different. Fine words are a mask to cover shady deeds. A sincere diplomat is like dry water or wooden iron.',
    'The Pope? How many divisions has he got?',
    'You know, they are fooling us, there is no God.',
    'We are fifty or a hundred years behind the advanced countries. We must make good this distance in ten years. Either we do it, or they will crush us.',
    'In the Soviet army it takes more courage to retreat than advance.',
    'The Red Army and Navy and the whole Soviet people must fight for every inch of Soviet soil, fight to the last drop of blood for our towns and villages...onward, to victory!',
    'Real liberty exists only there where exploitation has been annihilated, where no oppression of some peoples by others exists, where there is no unemployment and pauperism, where a person does not tremble because tomorrow he may lose his job, home and bread.',
    'You do not lament the loss of hair of one who has been beheaded.',
    'Have not fascism in Italy and National Socialism in Germany claimed that they have attained similar results [as in U.S.S.R.]? Have not both been achieved at the price of privation and personal liberty sacrificed for the good of the state?',
    'Mankind is divided into rich and poor, into property owners and exploited; and to abstract oneself from this fundamental division; and from the antagonism between poor and rich means abstracting oneself from fundamental facts.',
    'Marxism is not only the theory of socialism, it is an integral world outlook, a philosophical system, from which Marx’s proletarian socialism logically follows. This philosophical system is called dialectical materialism.',
    'music\'s a good thing, it calm the beast in the man.',
    'Our Red Army now needs IL-2 aircraft like the air it breathes, like the bread it eats.',
    'If the opposition disarms, well and good. If it refuses to disarm, we shall disarm it ourselves.',
    'Everyone imposes his own system as far as his army can reach.',
    'I know that after my death a pile of rubbish will be heaped on my grave, but the wind of History will sooner or later sweep it away without mercy',
    'In the future, there will be fewer but better Russians.',
    'When you chop wood, splinters fly',
    'Gaiety is the most outstanding feature of the Soviet Union.',
    'There is not, nor should there be, an irreconcilable contrast between the individual and the collective, between the interests of an individual person and the interests of the collective.',
    '[American Communist Party] legally exists in the U.S.A., it nominates its candidates in the elections, including Presidential elections.',
    'Remember how the first world war broke out. It broke out as a result of the desire to redivide the world.',
    'The writer is the engineer of the human soul.',
    'In war I would deal with the Devil and his grandmother',
    'We think that a powerful and vigorous movement is impossible without differences - "true conformity" is possible only in the cemetery.',
    'Artillery is the god of war.',
    'We [U.S.S.R. and U.S.A.] can exist peacefully together if we don\'t indulge in too much mutual fault-finding in all kinds of trifles',
    'Mr. Churchill, Mr. Prime Minister, how many divisions did you say that the pope had?',
    'Bukharin\'s a swine and surely worse than a swine because he thinks it below his dignity to write a couple of lines.',
    'Print is the sharpest and the strongest weapon of our party.',
    'If any foreign minister begins to defend to the death a \'peace conference,\' you can be sure his government has already placed its orders for new battleships and airplanes.',
    'You cannot make a revolution with silk gloves.',
    'American Communists have the opportunity to preach freely their ideas. It would be absolutely wrong to hold the Soviet government responsible for activities of the American Communists.',
    'Quantity has a quality all its own.',
    'I consider it completely unimportant who in the party will vote, or how; but what is extraordinarily important is this - who will count the votes, and how.',
    'We believe that the Anarchists are real enemies of Marxism.',
    'There are no fortresses that Bolsheviks cannot storm.',
    'The art of leadership is a serious matter. One must not lag behind a movement, because to do so is to become isolated from the masses. But one must not rush ahead, for to rush ahead is to lose contact with the masses. He who wished to lead a movement must conduct a fight on two fronts--against those who lag behind and those who rush ahead',
    'We Marxists believe that revolution will occur in other countries, as well. But it will occur at a time when it will be considered possible or necessary by revolutionaries of those countries.',
    'The Jews are not a nation!',
    'The situation is that in Germany capitalism has remained, classes and class struggle have remained which all the same will break into the open, which includes also the field of struggle of parties representing opposing classes just as it broke through in, let us say, Spain.',
    'Nowadays wars are not declared. They simply start.',
    'History shows that there are no invincible armies.',
    'Marxists have more than once pointed out that the capitalist world economic system contains in itself the seeds of a general crisis and of warlike clashes.',
    'Hitlers come and go, but Germany and the German people remain.',
    'The reason why there is now no communist government in Paris is because in the circumstances of 1945 the Soviet army was not able to reach French soil.',
    'This war is not an ordinary war. It is the war of the entire Russian people. Not only to eliminate the danger hanging over our heads, but to aid all people groaning under the yoke of Fascism',
    'Is it possible, then, to doubt that we can and must gain victory over the German invaders? The enemy is not as strong as some terror-stricken pseudo-intellectuals picture him. The devil is not as terrible as he is painted.',
    'I fail to see what dangers surrounding states can see in the ideas of the Soviet people if these states are really firmly seated in their saddles.',
    'Take some exercise, try to recover the look of a human being.',
    'American democracy and the Soviet system can exist simultaneously and compete peacefully. But one cannot develop into the other',
    'Our new Soviet constitution will, in my opinion, be the most democratic constitution of all those existing in the world.',
    'As you can see, even when [Adolf] Hitler desires to speak for peace, he cannot dispense with threats. This is symptomatic.',
    'Voters decide nothing. Vote counters decide everything!',
    'Each position, each metre of the Soviet territory must be stubbornly defended, to the last drop of blood. We must cling to every inch of Soviet soil and defend it to the end!',
    'We desire to give the Soviet people absolute liberty of voting for those they desire to elect, those whom they trust to ensure their interests.',
    'A certain inequality in regard to property still exists in a socialist society. But in a socialist society there is no unemployment, no exploitation, no oppression of nationalities.',
    'This war is not as in the past: whoever occupies a territory also imposes his own social system.',
    'Quanity has it\'s own quality.',
    'Writers are the engineers of human souls.',
    'I have in mind repeated statements by Japanese military men containing threats against other states.',
    'History shows that when a state is intent upon making war against another state, even though not adjacent, it begins to seek frontiers across which it could reach the frontiers of the state which it desires to attack. Usually, the aggressive state finds that frontier.',
    'In what do the activities of the Communist Parties consist? In what ways can they manifest themselves? These activities usually consist in the organization of working masses, in organizing meetings, demonstrations, strikes, etc. It is absolutely clear that American Communists cannot perform this in Soviet territory. The American workers are not in the U.S.S.R.',
    'Yes, the electoral struggle [in U.S.S.R.] will be animated. It will proceed around numerous very sharp questions, namely, practical questions having first-rate significance for the people.',
    'Only when we succeed in creating such an order under which people receive for their labor from the society not according to the quantity and quality of labor, but according to their needs, will it be possible to say that we have built up a communist society.',
    'Those who vote decide nothing. Those who count the vote decide everything.',
    'If things should go too far and deportation of all whiteguard emigres from the United States were demanded, this would be an attempt against the right of asylum promulgated in both the U.S.A. and the U.S.S.R.',
    '[State] finds [frontier] either with the aid of force, as in 1914, when Germany invaded Belgium in order to deal a blow against France or it "borrows" a frontier, such as Germany did with regard to Latvia, for instance, in 1918, in attempting to break through to Leningrad across Latvia.',
    'To assert that we desire to bring about revolution in other countries, by interfering with their lives, is to speak of something which does not exist and which we never preach.',
  ],
};
